---
name: Testing CI

on: [push, pull_request]

jobs:
  build:
    name: Testing Env

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [10.x, 12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run stuff
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          set -x
          if [[ "${{ github.event_name }}" = "pull_request" ]]; then
            echo "PR: ${{ github.event.pull_request.number }}"
          fi
